import dotenv from 'dotenv'

dotenv.config();
export const {
    API_VERTION,
    SECRET,
    SECRET_RECOVERY_EMAIL,
    MAILING_EMAIL_SIGNIN,
    MAILING_API_KEY_EMAIL,
    MAILING_URL_VALIDATE_EMAIL,
    PORT,
    DB_BDG,KEY,
    MYSQL_USER,
    MYSQL_HOST,
    MYSQL_PASSWORD,
    MYSQL_DATABASE,
    VERSION,
    APP_ENV,
    PROYECTO,
    PAIS,
    SECRET_IMG_SERVICE,
    WEB_DOMAIN,
    INTEGRATOR_ID,
    ACCESS_TOKEN,
    CUENTAS,
    CONTACTO,
    PERMITIDOS} = process.env;

